# Generated by Django 5.0.3 on 2024-11-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.FileField(upload_to='media/')),
                ('poster', models.ImageField(default=None, null=True, upload_to='media/')),
                ('songname', models.CharField(max_length=200)),
                ('Artist', models.CharField(max_length=300)),
                ('album_name', models.CharField(max_length=300)),
                ('lyrics', models.TextField()),
            ],
        ),
    ]
